name: Build & Test

run-name: "Build & Test -- ${{github.actor}} - ${{github.ref}}"

on:
  push:
    branches:
      - '*feature/*'
      - 'main'
      - 'dev'
      - 'qa'


jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: maven
          cache-dependency-path: |
             **/pom.xml
      - name: Maven Install
        run: mvn clean install
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: FilmDBJar